name: CI/CD workflow for Maven Build, Sonar Code scan 
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        
    - name: Build with Maven
      run: mvn clean install -f pom.xml
      
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v1
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=my-org
          -Dsonar.projectKey=appsec-Java-app
          -Dsonar.projectName=AppSEC-Java-app
          -Dsonar.projectVersion=1.0
          -Dsonar.sources=src/main/java/
          -Dsonar.language=java
          -Dsonar.java.binaries=target/classes 

      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

     # Check the Quality Gate status.
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after a short interval.
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 
    # Show the output from the Quality Gate. (`PASSED`, `WARN` or `FAILED`.)  
    - name: "SonarQube Quality Gate Status"
      run: echo "The Quality Gate is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}" 
  
